
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Properties;

import javax.swing.table.DefaultTableModel;

import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;



/**
 *
 * @author toosh
 */
public class teacherpanel extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public teacherpanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        model = new UtilDateModel();
        Properties propierties = new Properties();
        propierties.put("text.today", "Today");
        propierties.put("text.month", "Month");
        propierties.put("text.year", "Year");
        datePanel = new JDatePanelImpl(model, propierties);
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 750));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 800));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 102, 255));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jTextField1.setText(startApp.teacher.getFaculty());
        jTextField1.setBorder(null);
        jTextField1.setMinimumSize(new java.awt.Dimension(400, 48));
        jTextField1.setPreferredSize(new java.awt.Dimension(480, 80));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(102, 102, 255));
        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField11.setText(startApp.teacher.getName());
        jTextField11.setMaximumSize(new java.awt.Dimension(100, 38));
        jTextField11.setPreferredSize(new java.awt.Dimension(100, 38));
        jTextField11.setSelectedTextColor(new java.awt.Color(102, 102, 255));
        jTextField11.setSelectionColor(new java.awt.Color(102, 102, 255));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 102, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setText("Attendance sheet of date:");
        jTextField2.setMinimumSize(new java.awt.Dimension(180, 26));
        jTextField2.setPreferredSize(new java.awt.Dimension(195, 26));
        jTextField2.setSelectedTextColor(new java.awt.Color(102, 102, 255));
        jTextField2.setSelectionColor(new java.awt.Color(102, 102, 255));

        jComboBox1.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        String[] module = new String[startApp.teacher.getModule().size()];
        int i = 0;
        for(String s : startApp.teacher.getModule())
        {
            module[i] = s;
            i++;
        }
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(module));
        jComboBox1.setAlignmentX(1.0F);
        jComboBox1.setMinimumSize(new java.awt.Dimension(140, 26));
        jComboBox1.setPreferredSize(new java.awt.Dimension(140, 26));


        jButton2.setText("save");
        jButton2.setPreferredSize(new java.awt.Dimension(75, 26));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 680));

        jTable1.setBackground(new java.awt.Color(102, 102, 255));
        jTable1.setFont(new java.awt.Font("Montserrat Thin", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Student", "Attendence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setMinimumSize(new java.awt.Dimension(500, 500));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 1000));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(380, 500));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(102, 102, 255));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jTextField3.setText("Today's Attendance");
        jTextField3.setBorder(null);
        jTextField3.setMinimumSize(new java.awt.Dimension(280, 41));
        jTextField3.setSelectedTextColor(new java.awt.Color(102, 102, 255));
        jTextField3.setSelectionColor(new java.awt.Color(102, 102, 255));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(102, 102, 255));
        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setText("");
        jTextField4.setBorder(null);
        jTextField4.setSelectionColor(new java.awt.Color(255, 255, 255));

        jTextField5.setText("Enter student name...");
        jTextField5.setPreferredSize(new java.awt.Dimension(100, 22));

        jButton1.setText("Search");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(254, 384));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(204, 204, 255));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField6.setText("Input a Name to See details");
        jTextField6.setBorder(null);
        jTextField6.setMinimumSize(new java.awt.Dimension(120, 22));
        jTextField6.setPreferredSize(new java.awt.Dimension(120, 22));
        jTextField6.setSelectionColor(new java.awt.Color(255, 255, 255));


        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(204, 204, 255));
        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField7.setText("NaN");
        jTextField7.setBorder(null);
        jTextField7.setMinimumSize(new java.awt.Dimension(190, 50));
        jTextField7.setPreferredSize(new java.awt.Dimension(190, 46));
        jTextField7.setSelectionColor(new java.awt.Color(255, 255, 255));


        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(204, 204, 255));
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField8.setText("Days Attendended");
        jTextField8.setBorder(null);
        jTextField8.setSelectionColor(new java.awt.Color(255, 255, 255));


        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(204, 204, 255));
        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField9.setText("NaN");
        jTextField9.setBorder(null);
        jTextField9.setMinimumSize(new java.awt.Dimension(190, 50));
        jTextField9.setPreferredSize(new java.awt.Dimension(190, 46));
        jTextField9.setSelectionColor(new java.awt.Color(255, 255, 255));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(204, 204, 255));
        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField10.setText("Days Absent");
        jTextField10.setBorder(null);
        jTextField10.setSelectionColor(new java.awt.Color(255, 255, 255));


        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("View");
        jButton4.setPreferredSize(new java.awt.Dimension(85, 26));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 180, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 508, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        LocalDate d = LocalDate.now();
        System.out.print(","+d.getYear()+","+ d.getMonthValue()+","+d.getDayOfMonth());
        model.setDate(d.getYear(), d.getMonthValue()-1, d.getDayOfMonth());
        setValues();
        pack();
    }// </editor-fold>                        


    private void setValues()
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String module = (String) jComboBox1.getSelectedItem();
        int day = (this.model.getDay());
        int month = this.model.getMonth() +1;
        int year = this.model.getYear();
        System.out.print(day+","+month+","+year);
        date = LocalDate.of(year, month, day);
        System.out.print(date);
        System.out.print(LocalDate.now());/*
        if(date.compareTo(LocalDate.now())==0)
        {
            for(student s: startApp.s)
            {
                for(String m:s.getModule()) {
                    if(m.compareTo(module)==0)
                    {
                    	if
                        	model.addRow(new Object[]{s.getName(),null});
                    }
                }
            }   
        }
        else
        {*/
            for(student s: startApp.s)
            {
                for(Attendance a:s.getAttendance()) {
                    if(a.getModule().compareTo(module)==0 && date.compareTo(a.getDate())==0)
                    {
                        model.addRow(new Object[]{s.getName(),a.getPresence()});
                    }
                }
            }   
            
        //}
        jTable1.revalidate();
    }
    
	private void jButton4ActionPerformed(ActionEvent evt) {
		int day = (this.model.getDay());
        int month = this.model.getMonth() +1;
        int year = this.model.getYear();
        String module = (String) jComboBox1.getSelectedItem();
        LocalDate d = LocalDate.of(year, month, day);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int j = 0; j<model.getRowCount();j++)
        {
            model.removeRow(j);
            System.out.print(2);
            jTable1.revalidate();
            
        }
        if(model.getRowCount()> 0) {
        model.removeRow(model.getRowCount()-1);}
        for(student s: startApp.s)
        {
            for(Attendance a:s.getAttendance()) {
                if(a.getModule().compareTo(module)==0 && d.compareTo(a.getDate())==0)
                {
                    model.addRow(new Object[]{s.getName(),a.getPresence()});
                    System.out.print(s.getName() + a.getPresence() + a.getDate().toString());
                }
            }
        }
	}
                                      
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        login l = new login();
        l.setVisible(true);
        startApp.s.clear();
        this.dispose();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        //save
        database_connection dc = new database_connection();
        String module = (String)jComboBox1.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(this.date.compareTo(LocalDate.now())== 0) 
        {
            int count = model.getRowCount();
            for(int i = 0; i<count;i++)
            {
                String p = "P";
                int day = (this.model.getDay());
                int month = this.model.getMonth() +1;
                int year = this.model.getYear();
                LocalDate d = LocalDate.of(year, month, day);
                Boolean find = false;
    
                for(student s: startApp.s) {
                    if(s.getName().compareTo((String) model.getValueAt(i, 0)) == 0)
                    {
                        Boolean presence = (Boolean) model.getValueAt(i,1);
                        System.out.print(presence);
                        if(presence == null || presence == false)
                        {
                            presence = false;
                            p = "A";
                        }
                        int k = 0;
                        Attendance at = new Attendance(module,d,presence);
                        int findindex = 0;
    
                        for(Attendance a: s.getAttendance())
                        {
                            if(a.getDate().compareTo(at.getDate()) == 0 && a.getModule().compareTo(at.getModule()) == 0) {
                                find = true;
                                findindex = k;      
                            }
                            k++;
                        }
                        if(!find) {
                            s.getAttendance().add(at);
                            String query = "select mID from module where module_name = \""+module+"\"";
                            String mid = dc.connect(query).get(0).get(0);
                            int sID = s.getsID();
                            query = "insert into attendance values("+Integer.toString(sID)+","+mid+",\""+d.toString()+"\",\""+p+"\")";
                            dc.insQuery(query);
                        }
                        else {
                            System.out.print("ena deza");
                            s.getAttendance().remove(findindex);
                            s.getAttendance().add(at);
                            String query = "select mID from module where module_name = \""+module+"\"";
                            String mid = dc.connect(query).get(0).get(0);
                            System.out.println(p);
                            query = "update attendance set presence = \""+ p +"\""+ " where sID = "+Integer.toString(s.getsID())+" AND mID = " + mid+" AND entrydate =\""+(at.getDate().toString())+"\"" ;
                            dc.insQuery(query);
                        }
                    }
                }
            }
      
            
            
        cleanTable();
            }
        }                                        

    private void cleanTable()
    {
        String module = (String)jComboBox1.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for(int j = 0; j<model.getRowCount();j++)
        {
            model.removeRow(j);
            System.out.print(2);
            jTable1.revalidate();
            
        }
        model.removeRow(model.getRowCount()-1);
        for(student s: startApp.s)
        {
            for(Attendance a: s.getAttendance())
            {
                if(a.getModule().compareTo(module)==0 && date.compareTo(a.getDate()) == 0) {
                model.addRow(new Object[]{s.getName(),a.getPresence()});
                System.out.print(1);}
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	// 6 79
    	String name = jTextField5.getText();
    	int absent = 0, presence = 0;
    	for(student s: startApp.s)
    	{
    		if(s.getName().compareTo(name) == 0)
    		{
    			for(Attendance a: s.getAttendance())
    			{
    				if(a.getModule().compareTo((String)jComboBox1.getSelectedItem()) == 0)
	    				if(a.getPresence() == false)
	    				{
	    					absent++;
	    				}
	    				else {
	    					presence++;
	    				}
    			}
    			break;
    		}
    	}
    	jTextField6.setText(name);
    	jTextField7.setText(Integer.toString(presence));
    	jTextField9.setText(Integer.toString(absent));
		
	}

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private Boolean flagSearch;
    private JDatePanelImpl datePanel;
    private JDatePickerImpl datePicker;
    private UtilDateModel model;
    private LocalDate date;
    // End of variables declaration                   
}
